# Generated by Django 5.0.4 on 2024-04-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmovi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmovi',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
