# Generated by Django 5.0.4 on 2024-04-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmovi', '0002_filmovi_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmovi',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='movie-images'),
        ),
    ]
