# Generated by Django 5.0.4 on 2024-04-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmovi', '0003_filmovi_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmovi',
            name='datum',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='filmovi',
            name='godina',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='filmovi',
            name='imdb_ocena',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='filmovi',
            name='originalni_naziv',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='filmovi',
            name='zanr',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='filmovi',
            name='image',
            field=models.FileField(null=True, upload_to='movie-images'),
        ),
    ]
