# Generated by Django 5.0.4 on 2024-04-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmovi', '0005_rename_datum_filmovi_date_alter_filmovi_godina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmovi',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
