# Generated by Django 5.0.4 on 2024-04-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmovi', '0007_alter_filmovi_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmovi',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
