# Generated by Django 5.0.4 on 2024-04-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmovi', '0008_alter_filmovi_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmovi',
            options={},
        ),
    ]
