# Generated by Django 5.0.4 on 2024-04-26 08:32

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmovi', '0011_rename_tag_filmovi_tags'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmovi',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='filmovi',
            name='zanr',
        ),
        migrations.AddField(
            model_name='filmovi',
            name='zanr',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
