# Generated by Django 5.0.4 on 2024-04-26 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmovi', '0012_remove_filmovi_tags_remove_filmovi_zanr_filmovi_zanr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmovi',
            old_name='zanr',
            new_name='tags',
        ),
    ]
