# Generated by Django 5.0.4 on 2024-05-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmovi', '0013_rename_zanr_filmovi_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmovi',
            name='link_za_gledanje',
            field=models.CharField(default='', max_length=320),
        ),
        migrations.AddField(
            model_name='filmovi',
            name='link_za_preuzimanje',
            field=models.CharField(default='', max_length=320),
        ),
        migrations.AddField(
            model_name='filmovi',
            name='link_za_prevod',
            field=models.CharField(default='', max_length=320),
        ),
    ]
