# Generated by Django 5.0.4 on 2024-04-22 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serije', '0003_remove_serijesezona_sezona_delete_serijeepizode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epizode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epizode_date', models.DateField(auto_now_add=True)),
                ('epizode_link', models.CharField(max_length=300)),
                ('epizode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serije.serije')),
            ],
        ),
    ]
