# Generated by Django 5.0.4 on 2024-04-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serije', '0004_epizode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epizode',
            old_name='epizode',
            new_name='serija',
        ),
        migrations.AddField(
            model_name='epizode',
            name='epizoda',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
