# Generated by Django 5.0.4 on 2024-04-22 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serije', '0005_rename_epizode_epizode_serija_epizode_epizoda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sezona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sezona', models.CharField(blank=True, max_length=120, null=True)),
                ('serija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serije.serije')),
            ],
        ),
        migrations.CreateModel(
            name='Epizoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epizode_date', models.DateField(auto_now_add=True)),
                ('ep', models.CharField(blank=True, max_length=120, null=True)),
                ('epizode_link', models.CharField(max_length=300)),
                ('epizoda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serije.sezona')),
            ],
        ),
        migrations.DeleteModel(
            name='Epizode',
        ),
    ]
