# Generated by Django 5.0.4 on 2024-04-22 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serije', '0006_sezona_epizoda_delete_epizode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epizoda',
            name='epizoda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serije.serije'),
        ),
        migrations.AddField(
            model_name='epizoda',
            name='sezona',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='Sezona',
        ),
    ]
