# Generated by Django 5.0.4 on 2024-04-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serije', '0007_alter_epizoda_epizoda_epizoda_sezona_delete_sezona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epizoda',
            old_name='epizoda',
            new_name='epizode',
        ),
    ]
