# Generated by Django 5.0.4 on 2024-04-30 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domaci_filmovi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domacifilmovi',
            name='imdb_ocena',
        ),
        migrations.RemoveField(
            model_name='domacifilmovi',
            name='originalni_naziv',
        ),
    ]
