# Generated by Django 5.0.4 on 2024-04-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domaci_filmovi', '0002_remove_domacifilmovi_imdb_ocena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domacifilmovi',
            name='link_za_gledanje',
            field=models.CharField(default='', max_length=320),
        ),
        migrations.AddField(
            model_name='domacifilmovi',
            name='link_za_preuzimanje',
            field=models.CharField(default='', max_length=320),
        ),
    ]
