# Generated by Django 5.0.4 on 2024-04-30 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domace_serije', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epizoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epizode_date', models.DateField(auto_now_add=True)),
                ('sezona', models.CharField(blank=True, max_length=120, null=True)),
                ('ep', models.CharField(blank=True, max_length=120, null=True)),
                ('epizode_link', models.CharField(max_length=300)),
                ('epizode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domace_serije.domaceserije')),
            ],
        ),
    ]
